
puts "Destroy Bosses, Level Ranges and Loop Patterns"

Boss.destroy_all
LoopPattern.destroy_all
LevelRange.destroy_all
Message.destroy_all

puts "Create first Message..."

First_message   = Message.create(content: "First Message")

puts "Creating Level ranges..."

range_6to20     = LevelRange.create(number_of_bosses: 4, range:"Donjon 6 à 20")
range_21to35    = LevelRange.create(number_of_bosses: 3, range:"Donjon 21 à 35")
range_36to50    = LevelRange.create(number_of_bosses: 6, range:"Donjon 36 à 50")
range_51to65    = LevelRange.create(number_of_bosses: 7, range:"Donjon 51 à 65")
range_66to80    = LevelRange.create(number_of_bosses: 8, range:"Donjon 66 à 80")
range_81to95    = LevelRange.create(number_of_bosses: 8, range:"Donjon 81 à 95")
range_96to110   = LevelRange.create(number_of_bosses: 6, range:"Donjon 96 à 110")
range_111to125  = LevelRange.create(number_of_bosses: 8, range:"Donjon 111 à 125")
range_126to140  = LevelRange.create(number_of_bosses: 8, range:"Donjon 126 à 140")
range_141to155  = LevelRange.create(number_of_bosses: 7, range:"Donjon 141 à 155")
range_156to170  = LevelRange.create(number_of_bosses: 7, range:"Donjon 156 à 170")
range_171to185  = LevelRange.create(number_of_bosses: 6, range:"Donjon 171 à 185")
range_186to200  = LevelRange.create(number_of_bosses: 8, range:"Donjon 186 à 200")
range_201to215  = LevelRange.create(number_of_bosses: 7, range:"Donjon 201 à 215")
range_216to230  = LevelRange.create(number_of_bosses: 7, range:"Donjon 216 à 230")

puts "Creating Loop patterns..."

loop_6to20     = LoopPattern.create(level_range: range_6to20)
loop_21to35    = LoopPattern.create(level_range: range_21to35)
loop_36to50    = LoopPattern.create(level_range: range_36to50)
loop_51to65    = LoopPattern.create(level_range: range_51to65)
loop_66to80    = LoopPattern.create(level_range: range_66to80)
loop_81to95    = LoopPattern.create(level_range: range_81to95)
loop_96to110   = LoopPattern.create(level_range: range_96to110)
loop_111to125  = LoopPattern.create(level_range: range_111to125)
loop_126to140  = LoopPattern.create(level_range: range_126to140)
loop_141to155  = LoopPattern.create(level_range: range_141to155)
loop_156to170  = LoopPattern.create(level_range: range_156to170)
loop_171to185  = LoopPattern.create(level_range: range_171to185)
loop_186to200  = LoopPattern.create(level_range: range_186to200)
loop_201to215  = LoopPattern.create(level_range: range_201to215)
loop_216to230  = LoopPattern.create(level_range: range_216to230)

puts "Creating all Bosses !!!"
puts "Boss from 6 to 20..."

Boss.create(loop_pattern: loop_6to20, name: "Maine Cooyne",                                 location: "Mère Michou",                    url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/1816-maine-cooyne",                   first_encounter: 5,     second_encounter: 9,    third_encounter: 12,    first_modulox: 8,    second_modulox: 17,  third_modulox: 31)
Boss.create(loop_pattern: loop_6to20, name: "Shin Larve",                                   location: "Larventura",                     url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2157-shin-larve",                     first_encounter: 1,     second_encounter: 4,    third_encounter: 8,     first_modulox: 10,   second_modulox: 19,  third_modulox: 27)
Boss.create(loop_pattern: loop_6to20, name: "Bouftou Royal",                                location: "Pâturage des Bouftous",          url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/44-bouftou-royal",                    first_encounter: 2,     second_encounter: 7,    third_encounter: 11,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_6to20, name: "Tofu Royal",                                   location: "Tofulailler",                    url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/1259-tofu-royal",                     first_encounter: 3,     second_encounter: 6,    third_encounter: 10,    first_modulox: 2,    second_modulox: 24,  third_modulox: 28)

puts "Boss from 21 to 35..."

Boss.create(loop_pattern: loop_21to35, name: "Morfor",                                      location: "Caveau Relevé",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3216-morfor",                         first_encounter: 3,     second_encounter: 6,    third_encounter: 8,     first_modulox: 3,    second_modulox: 9,   third_modulox: 15)
Boss.create(loop_pattern: loop_21to35, name: "Abraknelle",                                  location: "Donjon des Abraknes",            url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4107-abraknelle",                     first_encounter: 2,     second_encounter: 5,    third_encounter: 9,     first_modulox: 4,    second_modulox: 14,  third_modulox: 36)
Boss.create(loop_pattern: loop_21to35, name: "Piou Royal",                                  location: "Piou Lahoupe",                   url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/1187-piou-royal",                     first_encounter: 1,     second_encounter: 4,    third_encounter: 7,     first_modulox: 12,   second_modulox: 23,  third_modulox: 30)

puts "Boss from 36 to 50..."

Boss.create(loop_pattern: loop_36to50, name: "Moogrr Royal",                                location: "Pâpaturage Royal",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4758-moogrr-royale",                  first_encounter: 2,     second_encounter: 5,    third_encounter: 15,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_36to50, name: "Craqueleur Royal",                            location: "Montagne Adezieu",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4519-craqueleur-royal",               first_encounter: 10,    second_encounter: 14,   third_encounter: 17,    first_modulox: 16,   second_modulox: 22,  third_modulox: 37)
Boss.create(loop_pattern: loop_36to50, name: "Plante Carnivore",                            location: "Champs Pourchan",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/1726-plante-carnivore",               first_encounter: 3,     second_encounter: 7,    third_encounter: 11,    first_modulox: 7,    second_modulox: 26,  third_modulox: 33)
Boss.create(loop_pattern: loop_36to50, name: "Agonie la Déterrée",                          location: "Tour Minérale",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4651-agonie-deterree",                first_encounter: 9,     second_encounter: 13,   third_encounter: 16,    first_modulox: 1,    second_modulox: 20,  third_modulox: 32)
Boss.create(loop_pattern: loop_36to50, name: "Hark Saniss, Dernier Géant",                  location: "Donjon des Morts-Brûlés",        url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5382-hark-saniss-dernier-geant",      first_encounter: 1,     second_encounter: 6,    third_encounter: 8,     first_modulox: 6,    second_modulox: 18,  third_modulox: 34)
Boss.create(loop_pattern: loop_36to50, name: "Pohl le poulpe",                              location: "Équipage du poulpe",             url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5376-pohl-poulpe",                    first_encounter: 4,     second_encounter: 12,   third_encounter: 18,    first_modulox: 21,   second_modulox: 29,  third_modulox: 39)


puts "Boss from 51 to 65..."

Boss.create(loop_pattern: loop_51to65, name: "Grand Bouftou Sauvage",                       location: "Antre Oubliée",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2768-grand-bouftou-sauvage",          first_encounter: 6,     second_encounter: 9,    third_encounter: 18,    first_modulox: 15,   second_modulox: 46,  third_modulox: 59)
Boss.create(loop_pattern: loop_51to65, name: "Throll",                                      location: "Donjon Bwork",                   url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2774-throll",                         first_encounter: 1,     second_encounter: 8,    third_encounter: 16,    first_modulox: 11,   second_modulox: 38,  third_modulox: 69)
Boss.create(loop_pattern: loop_51to65, name: "Royal Skouale",                               location: "Skouale Sèche",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4244-royal-skouale",                  first_encounter: 4,     second_encounter: 11,   third_encounter: 19,    first_modulox: 40,   second_modulox: 48,  third_modulox: 67)
Boss.create(loop_pattern: loop_51to65, name: "Kralaboss",                                   location: "Donjon Mollusky",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4240-kralaboss",                      first_encounter: 2,     second_encounter: 13,   third_encounter: 17,    first_modulox: 8,    second_modulox: 24,  third_modulox: 56)
Boss.create(loop_pattern: loop_51to65, name: "Grokokolantha",                               location: "Kokokolantha",                   url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4731-grokokolantha",                  first_encounter: 10,    second_encounter: 14,   third_encounter: 21,    first_modulox: 21,   second_modulox: 44,  third_modulox: 64)
Boss.create(loop_pattern: loop_51to65, name: "Cwabe Royal",                                 location: "Château de Cwabe",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4754-cwabe-royal",                    first_encounter: 5,     second_encounter: 7,    third_encounter: 20,    first_modulox: 4,    second_modulox: 31,  third_modulox: 53)
Boss.create(loop_pattern: loop_51to65, name: "Goël le golem",                               location: "Marteaux-Aigris",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5388-goel-golem",                     first_encounter: 3,     second_encounter: 12,   third_encounter: 15,    first_modulox: 7,    second_modulox: 14,  third_modulox: 50)

puts "Boss from 66 to 80..."

Boss.create(loop_pattern: loop_66to80, name: "Ratachouille",                                location: "Ratacombes",                     url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2313-ratachouille",                   first_encounter: 4,     second_encounter: 18,   third_encounter: 23,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_66to80, name: "Grand Orrok",                                 location: "Temple du Grand Orrok",          url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3587-grand-orrok",                    first_encounter: 2,     second_encounter: 14,   third_encounter: 15,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_66to80, name: "Korbot K-800",                                location: "Corbeau-Cave",                   url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3696-korbot-k-800",                   first_encounter: 5,     second_encounter: 10,   third_encounter: 21,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_66to80, name: "Hongrue, Haute Truche",                       location: "Truchière Abandonnée",           url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4871-hongrue-haute-truche",           first_encounter: 1,     second_encounter: 8,    third_encounter: 17,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_66to80, name: "Gligli Royal",                                location: "Domaine du Petit Groin",         url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4763-gligli-royal",                   first_encounter: 6,     second_encounter: 11,   third_encounter: 20,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_66to80, name: "Tsar Tsu Tsu",                                location: "Palais du Tsu",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4918-tsar-tsu-tsu",                   first_encounter: 7,     second_encounter: 12,   third_encounter: 24,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_66to80, name: "Lune Géante",                                 location: "Donjon Mulou",                   url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5114-lune-geante",                    first_encounter: 3,     second_encounter: 16,   third_encounter: 19,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_66to80, name: "Veuve Noire",                                 location: "Donjon Arakne",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5107-veuve-noire",                    first_encounter: 9,     second_encounter: 13,   third_encounter: 22,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Boss from 81 to 95..."

Boss.create(loop_pattern: loop_81to95, name: "Nonne",                                       location: "Sliptorium",                     url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/1786-nonne",                          first_encounter: 7,     second_encounter: 9,    third_encounter: 20,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_81to95, name: "Viktoria-France Kenstein",                    location: "Le Misolé",                      url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3735-viktoria-france-kenstein",       first_encounter: 1,     second_encounter: 10,   third_encounter: 17,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_81to95, name: "Vampyro",                                     location: "Château de Wagnar",              url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/1836-vampyro",                        first_encounter: 2,     second_encounter: 8,    third_encounter: 23,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_81to95, name: "El Pochito",                                  location: "Trool Academy",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2443-pochito",                        first_encounter: 6,     second_encounter: 14,   third_encounter: 22,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_81to95, name: "Bilbymoule Nacrée",                           location: "Le Hammamamoule",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2464-bilbymoule-nacree",              first_encounter: 4,     second_encounter: 12,   third_encounter: 19,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_81to95, name: "Reine Slek",                                  location: "Caverne des Slekymoses",         url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4251-reine-slek",                     first_encounter: 3,     second_encounter: 13,   third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_81to95, name: "Scarador",                                    location: "Scarrière Abandonnée",           url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4909-scaraboss",                      first_encounter: 11,    second_encounter: 16,   third_encounter: 24,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_81to95, name: "Chaferfu, le Roi Chafer",                     location: "Nécropoil de Morbax",            url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4739-chaferfu-roi-chafer",            first_encounter: 5,     second_encounter: 15,   third_encounter: 21,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Boss from 96 to 110..."

Boss.create(loop_pattern: loop_96to110, name: "Bilbyqueen",                                 location: "L'Arène Dansante",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2469-bilby-queen",                    first_encounter: 4,     second_encounter: 12,   third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_96to110, name: "Lady Glagla",                                location: "Glaglacier Cornu",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2363-lady-glagla",                    first_encounter: 2,     second_encounter: 5,    third_encounter: 15,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_96to110, name: "Yech'Ti'Wawa",                               location: "Niche du Yech'Ti'Wawa",          url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2368-yech-ti-wawa",                   first_encounter: 10,    second_encounter: 14,   third_encounter: 17,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_96to110, name: "Empereur Gelax",                             location: "Donjon Gelée",                   url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/1345-empereur-gelax",                 first_encounter: 1,     second_encounter: 6,    third_encounter: 8,     first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_96to110, name: "Chapo Magik",                                location: "Repaire des Magik Riktus",       url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4520-chapo-magik",                    first_encounter: 3,     second_encounter: 7,    third_encounter: 11,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_96to110, name: "Maitre Chuchoku",                            location: "Chuchobase",                     url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2100-maitre-chuchoku",                first_encounter: 9,     second_encounter: 13,   third_encounter: 16,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Boss from 111 to 125..."

Boss.create(loop_pattern: loop_111to125, name: "Hagën-Glass",                               location: "Pot d'Hagën-Glass",              url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2343-hagen-glass",                    first_encounter: 2,     second_encounter: 13,   third_encounter: 22,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_111to125, name: "Kya, Missiz Frizz",                         location: "L'Aile de l'Ambassadrice",       url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2348-kya-missiz-frizz",               first_encounter: 5,     second_encounter: 9,    third_encounter: 17,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_111to125, name: "Sylargh",                                   location: "Tour Gelée",                     url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2354-sylargh",                        first_encounter: 3,     second_encounter: 16,   third_encounter: 24,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_111to125, name: "Piktus",                                    location: "Donjon Cacterre",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2972-piktus",                         first_encounter: 6,     second_encounter: 14,   third_encounter: 21,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_111to125, name: "Spectrex le Tourmenteur",                   location: "Fosse du Tourmenteur",           url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2827-spectrex-tourmenteur",           first_encounter: 7,     second_encounter: 12,   third_encounter: 20,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_111to125, name: "Smarillion",                                location: "Caverne Smarrante",              url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4231-smarillion",                     first_encounter: 1,     second_encounter: 10,   third_encounter: 23,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_111to125, name: "Flaque Royale",                             location: "Donjon Flaqueux",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4720-flaque-royale",                  first_encounter: 4,     second_encounter: 11,   third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_111to125, name: "Zespadon Noir",                             location: "la Pichine",                     url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4727-zespadon-noir",                  first_encounter: 8,     second_encounter: 15,   third_encounter: 19,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Boss from 126 to 140..."

Boss.create(loop_pattern: loop_126to140, name: "Empeleul Lenald",                           location: "Palais Lenald",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2556-empeleul-lenald",                first_encounter: 12,    second_encounter: 15,   third_encounter: 22,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_126to140, name: "Emiw Black Wabbit",                         location: "Donjon Black Wabbit",            url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2563-emiw-black-wabbit",              first_encounter: 6,     second_encounter: 17,   third_encounter: 24,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_126to140, name: "Gwand Viziw Wabbit",                        location: "Donjon Wabbit",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2570-gwand-viziw-wabbit",             first_encounter: 3,     second_encounter: 8,    third_encounter: 19,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_126to140, name: "Mihmol l'Empaleur",                         location: "Sanctuaire de Mihmol",           url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3048-mihmol-empaleur",                first_encounter: 5,     second_encounter: 13,   third_encounter: 23,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_126to140, name: "Telob le Champmane",                        location: "Donjon Noirespore",              url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2977-telob-champmane",                first_encounter: 7,     second_encounter: 11,   third_encounter: 21,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_126to140, name: "Vilenya",                                   location: "la Fac Occultée",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3926-vilenya",                        first_encounter: 1,     second_encounter: 9,    third_encounter: 16,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_126to140, name: "Fripon",                                    location: "Donjon Phorreur",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4254-fripon",                         first_encounter: 2,     second_encounter: 10,   third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_126to140, name: "Chêne Mou",                                 location: "Donjon Abraknyde",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4874-chene-mou",                      first_encounter: 4,     second_encounter: 14,   third_encounter: 20,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Boss from 141 to 155..."

Boss.create(loop_pattern: loop_141to155, name: "Grand Prêtresse Sydonia",                   location: "le Vignoble Ignoble",            url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4060-grande-pretresse-sydonia",       first_encounter: 5,     second_encounter: 12,   third_encounter: 21,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_141to155, name: "Wa Wabbit",                                 location: "Château du Wa",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2582-wa-wabbit",                      first_encounter: 6,     second_encounter: 10,   third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_141to155, name: "Gwand Wabbit GM",                           location: "Wesewve de Cawottes Abandonnée", url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2605-gwand-wabbit-gm",                first_encounter: 3,     second_encounter: 11,   third_encounter: 20,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_141to155, name: "Venâme le Mangelombre",                     location: "Donjon Srambad",                 url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3080-vename-mangelombre",             first_encounter: 2,     second_encounter: 9,    third_encounter: 17,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_141to155, name: "Jamall'Auneth le Porte-clés",               location: "Donjon Enutrosor",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3094-jamall-auneth-porte-cles",       first_encounter: 8,     second_encounter: 13,   third_encounter: 15,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_141to155, name: "Blopgang Amadeus Blopzart",                 location: "Blopéra",                        url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4780-blopgang-amadeus-blopzart",      first_encounter: 4,     second_encounter: 14,   third_encounter: 19,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_141to155, name: "Bulbrute",                                  location: "Source du Mal",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5040-bulbrute",                       first_encounter: 1,     second_encounter: 7,    third_encounter: 16,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Boss from 156 to 170..."

Boss.create(loop_pattern: loop_156to170, name: "Vertox l'Intemporel",                       location: "Donjon Méka",                    url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3398-vertox-intemporel",              first_encounter: 9,     second_encounter: 15,   third_encounter: 20,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_156to170, name: "Raipiode l'Infréquençable",                 location: "Donjon E-Bou",                   url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3399-raipiode-infrequencable",        first_encounter: 1,     second_encounter: 6,    third_encounter: 11,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_156to170, name: "Kali",                                      location: "Repaire de Kali",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4217-kali",                           first_encounter: 3,     second_encounter: 8,    third_encounter: 17,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_156to170, name: "Le Riktus Masqué",                          location: "Donjon Riktus Elite",            url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4538-riktus-masque",                  first_encounter: 7,     second_encounter: 12,   third_encounter: 16,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_156to170, name: "Remington Smisse",                          location: "Roub'Bar",                       url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/2018-remington-smisse",               first_encounter: 4,     second_encounter: 10,   third_encounter: 21,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_156to170, name: "Javého",                                    location: "Lampionnaute",                   url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4924-javeho",                         first_encounter: 2,     second_encounter: 13,   third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_156to170, name: "Mamapoutre",                                location: "Patapoutrerie",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4923-mamapoutre",                     first_encounter: 5,     second_encounter: 14,   third_encounter: 19,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Boss from 171 to 185..."

Boss.create(loop_pattern: loop_171to185, name: "Roi Dunîl",                                 location: "Donjon Crocodaille",             url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3971-roi-dunil",                      first_encounter: 2,     second_encounter: 8,    third_encounter: 14,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_171to185, name: "Grozépine",                                 location: "Donjon Kannivore",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3866-grozepine",                      first_encounter: 1,     second_encounter: 6,    third_encounter: 10,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_171to185, name: "Kannistère",                                location: "Donjon Kanniboul",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3864-kannistere",                     first_encounter: 3,     second_encounter: 12,   third_encounter: 17,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_171to185, name: "Koko le Nutt",                              location: "Donjon des Tropikes",            url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/3865-koko-nutt",                      first_encounter: 11,    second_encounter: 15,   third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_171to185, name: "Pandore",                                   location: "Cité Interdite",                 url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5046-pandore",                        first_encounter: 4,     second_encounter: 9,    third_encounter: 13,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_171to185, name: "Maman Gerbouille",                          location: "Donjon Gerbouille",              url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5131-maman-gerbouille",               first_encounter: 5,     second_encounter: 7,    third_encounter: 16,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Boss from 186 to 200..."

Boss.create(loop_pattern: loop_186to200, name: "Blérwitch le Furax",                        location: "Tanière des Blérox",             url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4318-blerwitch-furax",                first_encounter: 2,     second_encounter: 11,   third_encounter: 13,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_186to200, name: "Sor'Hon, Seigneur de la Flamme",            location: "Volcan Or’Hodruin",              url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4327-sor-hon-seigneur-flamme",        first_encounter: 5,     second_encounter: 17,   third_encounter: 23,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_186to200, name: "Oeuf Antique",                              location: "Sanctuaire des Dragoeufs",       url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4400-oeuf-antique",                   first_encounter: 1,     second_encounter: 15,   third_encounter: 20,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_186to200, name: "Cendragon",                                 location: "Crête Givrée",                   url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4260-cendragon",                      first_encounter: 7,     second_encounter: 16,   third_encounter: 22,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_186to200, name: "Agonie Coeur-Cristal",                      location: "Tour Minérale",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/4664-agonie-coeur-cristal",           first_encounter: 3,     second_encounter: 8,    third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_186to200, name: "Fantôme du Tanukouï-San",                   location: "Tombeau de Pandala",             url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5059-fantome-tanukoui-san",           first_encounter: 4,     second_encounter: 9,    third_encounter: 19,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_186to200, name: "Fléogre",                                   location: "Canyon des Fléopards",           url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5052-fleogre",                        first_encounter: 6,     second_encounter: 12,   third_encounter: 21,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_186to200, name: "Granduk",                                   location: "Usine Hibourg",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5137-granduk-hibourg",                first_encounter: 10,    second_encounter: 14,   third_encounter: 24,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Boss from 201 to 215..."

Boss.create(loop_pattern: loop_201to215, name: "Bufflamboyant",                             location: "Donjon Toundrasoir",             url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5188-bufflamboyant",                  first_encounter: 7,     second_encounter: 12,   third_encounter: 16,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_201to215, name: "Crustacérébro",                             location: "Donjon Crustargneux",            url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5182-crustacerebro",                  first_encounter: 3,     second_encounter: 8,    third_encounter: 17,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_201to215, name: "Scorpiétineur",                             location: "Donjon Cagnardeur",              url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5176-scorpietineur",                  first_encounter: 1,     second_encounter: 6,    third_encounter: 11,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_201to215, name: "Phacochemar",                               location: "Donjon Vandaliéné",              url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5170-phacochemar",                    first_encounter: 9,     second_encounter: 15,   third_encounter: 20,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_201to215, name: "Casse-Cours",                               location: "Donjon Plantigarde",             url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5241-casse-cours",                    first_encounter: 2,     second_encounter: 13,   third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_201to215, name: "Sumorse",                                   location: "Donjon Mansot",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5247-sumorse",                        first_encounter: 5,     second_encounter: 14,   third_encounter: 19,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_201to215, name: "Tortumulte",                                location: "Donjon Carapatte",               url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5235-tortumulte",                     first_encounter: 4,     second_encounter: 10,   third_encounter: 21,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_201to215, name: "Agonie, Nécomancienne livide",              location: "Tour Minérale",                  url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5229-agonie-necromancienne-livide",   first_encounter: 0,     second_encounter: 0,    third_encounter: 0,     first_modulox: 0,    second_modulox: 0,   third_modulox: 0)


puts "Boss from 216 to 230"

Boss.create(loop_pattern: loop_216to230, name: "Vaal’Enthia, Reine-démone",                 location: "Donjon Phytomorphe",             url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5277-vaal-enthia-reine-demone",       first_encounter: 9,     second_encounter: 15,   third_encounter: 20,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_216to230, name: "Ar’Nan, Augure du néant",                   location: "Donjon Vidéant",                 url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5283-ar-nan-augure-neant",            first_encounter: 1,     second_encounter: 6,    third_encounter: 11,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_216to230, name: "Cratéros, Bourreau de la fin",              location: "Donjon Démhorrible",             url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5289-crateros-bourreau-fin",          first_encounter: 3,     second_encounter: 8,    third_encounter: 17,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_216to230, name: "!@#dh`~",                                   location: "Donjon Égaré ?",                 url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5295-dh",                             first_encounter: 7,     second_encounter: 12,   third_encounter: 16,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_216to230, name: "K’abah’al, Gardien de la route des morts",  location: "Donjon Ravageur",                url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5301-k-abah-gardien-route-morts",     first_encounter: 4,     second_encounter: 10,   third_encounter: 21,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_216to230, name: "Sir Comte Flex",                            location: "Donjon Steamer",                 url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5400-sir-comte-flex",                 first_encounter: 5,     second_encounter: 14,   third_encounter: 19,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)
Boss.create(loop_pattern: loop_216to230, name: "Raeliss",                                   location: "Donjon Poisseux Abyssaux",       url_fr: "https://www.wakfu.com/fr/mmorpg/encyclopedie/monstres/5394-raeliss",                        first_encounter: 2,     second_encounter: 13,   third_encounter: 18,    first_modulox: 0,    second_modulox: 0,   third_modulox: 0)

puts "Seed generated"
